// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: api/ocp-problem-api/ocp-problem-api.proto

package ocp_problem_api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProblemV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId uint64 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Text   string `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *ProblemV1) Reset() {
	*x = ProblemV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_problem_api_ocp_problem_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProblemV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProblemV1) ProtoMessage() {}

func (x *ProblemV1) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_problem_api_ocp_problem_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProblemV1.ProtoReflect.Descriptor instead.
func (*ProblemV1) Descriptor() ([]byte, []int) {
	return file_api_ocp_problem_api_ocp_problem_api_proto_rawDescGZIP(), []int{0}
}

func (x *ProblemV1) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProblemV1) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ProblemV1) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ResultSaveV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ResultSaveV1) Reset() {
	*x = ResultSaveV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_problem_api_ocp_problem_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResultSaveV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultSaveV1) ProtoMessage() {}

func (x *ResultSaveV1) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_problem_api_ocp_problem_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultSaveV1.ProtoReflect.Descriptor instead.
func (*ResultSaveV1) Descriptor() ([]byte, []int) {
	return file_api_ocp_problem_api_ocp_problem_api_proto_rawDescGZIP(), []int{1}
}

func (x *ResultSaveV1) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ProblemQueryV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ProblemQueryV1) Reset() {
	*x = ProblemQueryV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_problem_api_ocp_problem_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProblemQueryV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProblemQueryV1) ProtoMessage() {}

func (x *ProblemQueryV1) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_problem_api_ocp_problem_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProblemQueryV1.ProtoReflect.Descriptor instead.
func (*ProblemQueryV1) Descriptor() ([]byte, []int) {
	return file_api_ocp_problem_api_ocp_problem_api_proto_rawDescGZIP(), []int{2}
}

func (x *ProblemQueryV1) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ProblemFilterV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids     []uint64 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	UserIds []uint64 `protobuf:"varint,2,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
}

func (x *ProblemFilterV1) Reset() {
	*x = ProblemFilterV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_problem_api_ocp_problem_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProblemFilterV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProblemFilterV1) ProtoMessage() {}

func (x *ProblemFilterV1) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_problem_api_ocp_problem_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProblemFilterV1.ProtoReflect.Descriptor instead.
func (*ProblemFilterV1) Descriptor() ([]byte, []int) {
	return file_api_ocp_problem_api_ocp_problem_api_proto_rawDescGZIP(), []int{3}
}

func (x *ProblemFilterV1) GetIds() []uint64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *ProblemFilterV1) GetUserIds() []uint64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type ProblemListQueryV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filter *ProblemFilterV1 `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	Limit  uint64           `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset uint64           `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *ProblemListQueryV1) Reset() {
	*x = ProblemListQueryV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_problem_api_ocp_problem_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProblemListQueryV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProblemListQueryV1) ProtoMessage() {}

func (x *ProblemListQueryV1) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_problem_api_ocp_problem_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProblemListQueryV1.ProtoReflect.Descriptor instead.
func (*ProblemListQueryV1) Descriptor() ([]byte, []int) {
	return file_api_ocp_problem_api_ocp_problem_api_proto_rawDescGZIP(), []int{4}
}

func (x *ProblemListQueryV1) GetFilter() *ProblemFilterV1 {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *ProblemListQueryV1) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ProblemListQueryV1) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ProblemListV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*ProblemV1 `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *ProblemListV1) Reset() {
	*x = ProblemListV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_problem_api_ocp_problem_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProblemListV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProblemListV1) ProtoMessage() {}

func (x *ProblemListV1) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_problem_api_ocp_problem_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProblemListV1.ProtoReflect.Descriptor instead.
func (*ProblemListV1) Descriptor() ([]byte, []int) {
	return file_api_ocp_problem_api_ocp_problem_api_proto_rawDescGZIP(), []int{5}
}

func (x *ProblemListV1) GetList() []*ProblemV1 {
	if x != nil {
		return x.List
	}
	return nil
}

type ProblemResultV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsSuccess bool   `protobuf:"varint,1,opt,name=is_success,json=isSuccess,proto3" json:"is_success,omitempty"`
	Id        uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Text      string `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *ProblemResultV1) Reset() {
	*x = ProblemResultV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_problem_api_ocp_problem_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProblemResultV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProblemResultV1) ProtoMessage() {}

func (x *ProblemResultV1) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_problem_api_ocp_problem_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProblemResultV1.ProtoReflect.Descriptor instead.
func (*ProblemResultV1) Descriptor() ([]byte, []int) {
	return file_api_ocp_problem_api_ocp_problem_api_proto_rawDescGZIP(), []int{6}
}

func (x *ProblemResultV1) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

func (x *ProblemResultV1) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProblemResultV1) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_api_ocp_problem_api_ocp_problem_api_proto protoreflect.FileDescriptor

var file_api_ocp_problem_api_ocp_problem_api_proto_rawDesc = []byte{
	0x0a, 0x29, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x63, 0x70, 0x2d, 0x70, 0x72, 0x6f, 0x62, 0x6c, 0x65,
	0x6d, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x63, 0x70, 0x2d, 0x70, 0x72, 0x6f, 0x62, 0x6c, 0x65,
	0x6d, 0x2d, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x6f, 0x63, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x2e, 0x61, 0x70, 0x69, 0x1a, 0x1c, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x48, 0x0a, 0x09, 0x50, 0x72,
	0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x56, 0x31, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x65, 0x78, 0x74, 0x22, 0x1e, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x53, 0x61,
	0x76, 0x65, 0x56, 0x31, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x20, 0x0a, 0x0e, 0x50, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x56, 0x31, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0x3e, 0x0a, 0x0f, 0x50, 0x72, 0x6f, 0x62, 0x6c, 0x65,
	0x6d, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x56, 0x31, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x04, 0x52, 0x03, 0x69, 0x64, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x04, 0x52, 0x07, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x73, 0x22, 0x7c, 0x0a, 0x12, 0x50, 0x72, 0x6f, 0x62, 0x6c, 0x65,
	0x6d, 0x4c, 0x69, 0x73, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x56, 0x31, 0x12, 0x38, 0x0a, 0x06,
	0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6f,
	0x63, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x50,
	0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x56, 0x31, 0x52, 0x06,
	0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x6f, 0x66,
	0x66, 0x73, 0x65, 0x74, 0x22, 0x3f, 0x0a, 0x0d, 0x50, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x4c,
	0x69, 0x73, 0x74, 0x56, 0x31, 0x12, 0x2e, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x62, 0x6c, 0x65,
	0x6d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x56, 0x31, 0x52,
	0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x54, 0x0a, 0x0f, 0x50, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x56, 0x31, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x73, 0x5f, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73,
	0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x32, 0xb2, 0x03, 0x0a, 0x0a,
	0x4f, 0x63, 0x70, 0x50, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x12, 0x63, 0x0a, 0x0f, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x56, 0x31, 0x12, 0x1a, 0x2e,
	0x6f, 0x63, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x50, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x56, 0x31, 0x1a, 0x1d, 0x2e, 0x6f, 0x63, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x53, 0x61, 0x76, 0x65, 0x56, 0x31, 0x22, 0x15, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0f,
	0x22, 0x0a, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x3a, 0x01, 0x2a, 0x12,
	0x67, 0x0a, 0x11, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x50, 0x72, 0x6f, 0x62, 0x6c,
	0x65, 0x6d, 0x56, 0x31, 0x12, 0x1f, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x62, 0x6c,
	0x65, 0x6d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x56, 0x31, 0x1a, 0x1a, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x62,
	0x6c, 0x65, 0x6d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x56,
	0x31, 0x22, 0x15, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0f, 0x12, 0x0d, 0x2f, 0x76, 0x31, 0x2f, 0x73,
	0x68, 0x6f, 0x77, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x12, 0x67, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74,
	0x50, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x73, 0x56, 0x31, 0x12, 0x23, 0x2e, 0x6f, 0x63, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x72, 0x6f,
	0x62, 0x6c, 0x65, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x56, 0x31, 0x1a,
	0x1e, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x50, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x31, 0x22,
	0x10, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0a, 0x12, 0x08, 0x2f, 0x76, 0x31, 0x2f, 0x6c, 0x69, 0x73,
	0x74, 0x12, 0x6d, 0x0a, 0x0f, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x50, 0x72, 0x6f, 0x62, 0x6c,
	0x65, 0x6d, 0x56, 0x31, 0x12, 0x1f, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x62, 0x6c,
	0x65, 0x6d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x56, 0x31, 0x1a, 0x20, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x62,
	0x6c, 0x65, 0x6d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x56, 0x31, 0x22, 0x17, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x11, 0x2a,
	0x0f, 0x2f, 0x76, 0x31, 0x2f, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x2f, 0x7b, 0x69, 0x64, 0x7d,
	0x42, 0x47, 0x5a, 0x45, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f,
	0x7a, 0x6f, 0x6e, 0x63, 0x70, 0x2f, 0x6f, 0x63, 0x70, 0x2d, 0x70, 0x72, 0x6f, 0x62, 0x6c, 0x65,
	0x6d, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x6f, 0x63, 0x70, 0x2d, 0x70, 0x72,
	0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x2d, 0x61, 0x70, 0x69, 0x3b, 0x6f, 0x63, 0x70, 0x5f, 0x70, 0x72,
	0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_api_ocp_problem_api_ocp_problem_api_proto_rawDescOnce sync.Once
	file_api_ocp_problem_api_ocp_problem_api_proto_rawDescData = file_api_ocp_problem_api_ocp_problem_api_proto_rawDesc
)

func file_api_ocp_problem_api_ocp_problem_api_proto_rawDescGZIP() []byte {
	file_api_ocp_problem_api_ocp_problem_api_proto_rawDescOnce.Do(func() {
		file_api_ocp_problem_api_ocp_problem_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_ocp_problem_api_ocp_problem_api_proto_rawDescData)
	})
	return file_api_ocp_problem_api_ocp_problem_api_proto_rawDescData
}

var file_api_ocp_problem_api_ocp_problem_api_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_ocp_problem_api_ocp_problem_api_proto_goTypes = []interface{}{
	(*ProblemV1)(nil),          // 0: ocp.problem.api.ProblemV1
	(*ResultSaveV1)(nil),       // 1: ocp.problem.api.ResultSaveV1
	(*ProblemQueryV1)(nil),     // 2: ocp.problem.api.ProblemQueryV1
	(*ProblemFilterV1)(nil),    // 3: ocp.problem.api.ProblemFilterV1
	(*ProblemListQueryV1)(nil), // 4: ocp.problem.api.ProblemListQueryV1
	(*ProblemListV1)(nil),      // 5: ocp.problem.api.ProblemListV1
	(*ProblemResultV1)(nil),    // 6: ocp.problem.api.ProblemResultV1
}
var file_api_ocp_problem_api_ocp_problem_api_proto_depIdxs = []int32{
	3, // 0: ocp.problem.api.ProblemListQueryV1.filter:type_name -> ocp.problem.api.ProblemFilterV1
	0, // 1: ocp.problem.api.ProblemListV1.list:type_name -> ocp.problem.api.ProblemV1
	0, // 2: ocp.problem.api.OcpProblem.CreateProblemV1:input_type -> ocp.problem.api.ProblemV1
	2, // 3: ocp.problem.api.OcpProblem.DescribeProblemV1:input_type -> ocp.problem.api.ProblemQueryV1
	4, // 4: ocp.problem.api.OcpProblem.ListProblemsV1:input_type -> ocp.problem.api.ProblemListQueryV1
	2, // 5: ocp.problem.api.OcpProblem.RemoveProblemV1:input_type -> ocp.problem.api.ProblemQueryV1
	1, // 6: ocp.problem.api.OcpProblem.CreateProblemV1:output_type -> ocp.problem.api.ResultSaveV1
	0, // 7: ocp.problem.api.OcpProblem.DescribeProblemV1:output_type -> ocp.problem.api.ProblemV1
	5, // 8: ocp.problem.api.OcpProblem.ListProblemsV1:output_type -> ocp.problem.api.ProblemListV1
	6, // 9: ocp.problem.api.OcpProblem.RemoveProblemV1:output_type -> ocp.problem.api.ProblemResultV1
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_ocp_problem_api_ocp_problem_api_proto_init() }
func file_api_ocp_problem_api_ocp_problem_api_proto_init() {
	if File_api_ocp_problem_api_ocp_problem_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_ocp_problem_api_ocp_problem_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProblemV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_problem_api_ocp_problem_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResultSaveV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_problem_api_ocp_problem_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProblemQueryV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_problem_api_ocp_problem_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProblemFilterV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_problem_api_ocp_problem_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProblemListQueryV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_problem_api_ocp_problem_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProblemListV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_problem_api_ocp_problem_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProblemResultV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_ocp_problem_api_ocp_problem_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_ocp_problem_api_ocp_problem_api_proto_goTypes,
		DependencyIndexes: file_api_ocp_problem_api_ocp_problem_api_proto_depIdxs,
		MessageInfos:      file_api_ocp_problem_api_ocp_problem_api_proto_msgTypes,
	}.Build()
	File_api_ocp_problem_api_ocp_problem_api_proto = out.File
	file_api_ocp_problem_api_ocp_problem_api_proto_rawDesc = nil
	file_api_ocp_problem_api_ocp_problem_api_proto_goTypes = nil
	file_api_ocp_problem_api_ocp_problem_api_proto_depIdxs = nil
}
